name: Check and test the source code
on:
  pull_request:
    branches:
      - main
jobs:
  check_typo:
    name: Check typo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '20'
      - run: npm install -g npm@latest
      - run: npm install cspell
      - run: npx cspell '**' --gitignore --no-progress
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.13.1'
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
      - name: Rebuild the mock file
        run: |
          if [[ $(git diff --name-only HEAD | grep 'lib/src/run_with_network_images.mocks.dart' || echo '') != "" ]]; then
            RED="\e[31m"
            END_COLOR="\e[0m"

            echo ""
            echo -e "${RED}The committed run_with_network_images.mocks.dart file does not match with the generated file.${END_COLOR}"
            echo -e "${RED}Please execute the following command and commit the result file.${END_COLOR}"
            echo -e "${RED}flutter pub run build_runner build --delete-conflicting-outputs${END_COLOR}"
            echo ""

            exit 1
          fi
